#!/usr/bin/env bash

cd "${0%/*}"

if [ -n "$XDG_DATA_HOME" ]; then
	APPSDIR="$XDG_DATA_HOME/applications"
else
	APPSDIR="$HOME/.local/share/applications"
fi

type mono 2>/dev/null >&2 || {
	echo "Mono is missing, it will be installed"
	sudo apt update
	sudo apt install -y gnupg ca-certificates
	sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys 3FA7E0328081BFF6A14DA29AA6A19B38D3D831EF
	echo "deb https://download.mono-project.com/repo/ubuntu stable-bionic main" | sudo tee /etc/apt/sources.list.d/mono-official-stable.list
	sudo apt update
	sudo apt install -y mono-complete
}

[ -f "/usr/lib/aarch64-linux-gnu/liblua5.3.so" ] || {
	echo "liblua is missing, it will be installed"
	sudo apt update
	sudo apt install -y liblua5.3 libcurl3
}

[ -e "lib-arm64/liblua53.so" ] || {
	ln -s /usr/lib/aarch64-linux-gnu/liblua5.3.so lib-arm64/liblua53.so
}

[ -e "lib-arm64/libfmod.so.13" ] || {
	ln -s libfmod.so.13.6 lib-arm64/libfmod.so.13
	ln -s libfmodstudio.so.13.6 lib-arm64/libfmodstudio.so.13
}

[ -f ~/.config/Olympus/config.json -o -d ~/.olympus ] || {
	echo "Olympus is missing, it will be installed"
	sudo apt update
	sudo apt install -y wget
	celeste_path="$(pwd)"
	pushd /tmp
	wget -O Olympus.zip https://github.com/pixelomer/Celeste-ARM64/releases/download/2021.09.07/Olympus.zip
	unzip Olympus.zip
	mv Olympus ~/.olympus
	rm Olympus.zip
	popd
	pushd ~/.olympus
	sed 's/read/answer\=y\;\#/g' < ./install.sh > install-nocheck.sh
	chmod +x install-nocheck.sh
	./install-nocheck.sh
	popd
	mkdir -p ~/.config/Olympus
	cat > ~/.config/Olympus/config.json <<EOF
{
  "installs":[{
    "type":"manual",
    "name":"Celeste",
    "path":"${celeste_path}"
  }]
}
EOF
	popd
}

cat > "${APPSDIR}/Celeste.desktop" <<EOF
[Desktop Entry]
Type=Application
Version=1.0
Name=Celeste
Comment=Celeste
Exec=$(pwd)/Celeste
Icon=$(pwd)/Celeste.png
Terminal=false
Categories=Game;Application;
EOF
update-desktop-database "${APPSDIR}"

rm -f System*.dll mscorlib.dll Mono.Posix.dll Mono.Security.dll monoconfig monomachineconfig

LD_PRELOAD="$(pwd)/fmod_preload.so" LD_LIBRARY_PATH="$(pwd)/lib-arm64" mono Celeste.exe