#!/usr/bin/env bash

set -e
cd "${0%/*}"

if [ -n "$XDG_DATA_HOME" ]; then
	APPSDIR="$XDG_DATA_HOME/applications"
else
	APPSDIR="$HOME/.local/share/applications"
fi

type dotnet 2>/dev/null >&2 || {
	echo ".NET is missing, it will be installed"
	sudo apt update
	sudo apt install -y dotnet8
}

[ -f "/usr/lib/aarch64-linux-gnu/liblua5.4.so.0" ] || {
	echo "liblua is missing, it will be installed"
	sudo apt update
	sudo apt install -y liblua5.4-0
}

[ -e "lib-arm64/liblua54.so" ] || {
	ln -s /usr/lib/aarch64-linux-gnu/liblua5.4.so.0 lib-arm64/liblua54.so
}

[ -e "MiniInstaller.dll" ] || {
	echo "Installing Everest"
	wget "https://github.com/EverestAPI/Everest/releases/latest/download/main.zip"
	unzip main.zip
	rsync -ar main/ ./
	rm -rf main main.zip
	dotnet MiniInstaller.dll
}

cat > "${APPSDIR}/Celeste.desktop" <<EOF
[Desktop Entry]
Type=Application
Version=1.0
Name=Celeste
Comment=Celeste
Exec=$(pwd)/Celeste-arm64
Icon=$(pwd)/Celeste.png
Terminal=false
Categories=Game;Application;
EOF
update-desktop-database "${APPSDIR}"

rm -rf lib64-linux
cat > Celeste <<'EOF'
#!/usr/bin/env bash
exec dotnet Celeste.dll
EOF
chmod +x Celeste
LD_LIBRARY_PATH="$(pwd)/lib-arm64:${LD_LIBRARY_PATH}" exec dotnet Celeste.dll
