FROM ubuntu:noble
RUN apt-get update
RUN apt-get install -y cmake
RUN apt-get install -y make
RUN apt-get install -y libsdl2-dev
RUN apt-get install -y sudo
RUN apt-get install -y gcc
RUN apt-get install -y git
RUN apt-get install -y curl
RUN apt-get install -y jq
RUN apt-get install -y sed
RUN git config --global core.fscache false
